let static SP = 0;

extern fun add(a, b);
extern fun sub(a, b);
extern fun puts(value);
extern fun puti(value);
extern fun puthex(value);
extern fun putarr(ptr, len);
extern fun putchar(value);
extern fun putln();
extern fun deref(value);
extern fun idx(ptr, i);
extern fun memcpy(dst, src, count);
extern fun malloc(dst, src, count);
let static STACK = 0;
STACK = malloc(1024);

fun new_scope() {
    puts("New scope at SP=");
    puti(SP);
    putln();
    return SP;
}

fun push(value) {
    puts("Storing ");puti(value);putln();
    SP = add(SP, 1);
    puts("SP=");puti(SP);putln();
    puts("STACK=");puti(STACK);putln();
    puts("idx(STACK, SP)=");puti(idx(STACK, SP));putln();
    idx(STACK, SP) = value;
}

fun pop() {
    let value = deref(idx(STACK, SP));
    SP = add(SP, -1);
    return value;
}

fun poparr(ptr, count) {
    while (count) {
        count = add(count, -1);
        idx(ptr, count) = pop();
    }
}

fun pusharr(ptr, count) {
    let i = 0;
    while (count) {
        count = add(count, -1);
        push(deref(idx(ptr, i)));
        i = add(i, 1);
    }
}

fun ret(ebp, count) {
    let current_sp = SP;
    // Revert stack pointer
    SP = add(ebp, count);
    puts("Return from scope at SP=");
    puti(SP);
    putln();
    // Copy return values to stack
    memcpy(idx(STACK, ebp), idx(STACK, current_sp), count);
} 

fun test() {
    let ebp = new_scope();
    push(1);
    push(2);
    push(3);
    ret(ebp, 3);
}

fun test2() {
    let a = pop();
    let b = pop();
    let c = pop();
    let ebp = new_scope();

    let total = add(add(a, b), c);
    push(total);
    
    ret(ebp, 1);
}


fun main() {
    test();
    test2();
    let a = pop();
    puti(a);
    putln();
}

main();